on:
  push

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.AUTO_PR_TOKEN }}
          commit-message: '' # Não será criado um commit
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: feat/content # Branch de origem (source branch)
          base: main # Branch de destino (target branch)
          delete-branch: false
          title: Pull Request from feature/post to main
          body: |
            Este Pull Request foi criado automaticamente para mesclar feature/post em main.
          labels: |
            automated pr
          assignees: GabrielL915
          draft: false
